import type { Metadata } from 'next'
import './globals.css'
import type { PropsWithChildren } from 'react'

export const metadata: Metadata = {
  title: 'NapFlow WebUI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<PropsWithChildren>) {
  return (
    <html lang="zh">
      <body>
        {children}
      </body>
    </html>
  )
}
